const messages=[
["Entrega o teu caminho ao Senhor; confia nele, e o mais Ele fará.","Fé","Salmos 37:5"],["Quando tudo parecer difícil, lembre-se: você não está sozinho. Deus caminha com você.","Esperança","Isaías 41:10"],["Que Deus ilumine seus caminhos, proteja sua família e encha seu coração de paz.","Proteção","Salmos 121:7"],["Não desista. Muitas vezes a bênção está mais perto do que você imagina.","Esperança","Romanos 12:12"],["Comece o dia agradecendo. Cada novo amanhecer é uma oportunidade de recomeçar.","Bom dia","Salmos 118:24"],["Que a paz de Deus entre em sua casa e permaneça em seu coração nesta noite.","Boa noite","João 14:27"],["Tenha coragem para continuar. Deus conhece suas lutas e vê cada lágrima.","Força","Josué 1:9"],["A oração muda o coração, fortalece a esperança e nos aproxima de Deus.","Oração","Filipenses 4:6"],["Mesmo sem entender o caminho, continue confiando. Deus sabe para onde está levando você.","Confiança","Provérbios 3:5"],["Que nunca falte fé para acreditar, força para continuar e esperança para recomeçar.","Fé","Hebreus 11:1"],["Deus pode transformar um momento difícil em um testemunho de vitória.","Vitória","Salmos 30:5"],["Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.","Proteção","Salmos 46:1"],["Tudo posso naquele que me fortalece.","Força","Filipenses 4:13"],["O Senhor é o meu pastor; nada me faltará.","Fé","Salmos 23:1"]
];
let current=0;
const $=id=>document.getElementById(id), statusEl=$("status");
function favorites(){return JSON.parse(localStorage.getItem("fe_favoritos")||"[]")}
function setMessage(i){current=i;$("heroVerse").textContent=messages[i][0];$("heroRef").textContent=messages[i][2];renderFavorites()}
function renderFavorites(){const box=$("favorites"),f=favorites();if(!f.length){box.innerHTML='<div class="empty-fav">Ainda não há mensagens favoritas. Toque no coração para guardar uma. ❤️</div>';return}box.innerHTML=f.slice(0,3).map(i=>`<article class="favorite-item"><span class="heart" data-remove="${i}">♥</span><p>${messages[i][0]}</p><strong>${messages[i][2]}</strong></article>`).join("");box.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{const n=Number(b.dataset.remove);localStorage.setItem("fe_favoritos",JSON.stringify(favorites().filter(x=>x!==n)));renderFavorites()})}
function newMessage(category){let list=messages.map((m,i)=>({m,i})).filter(x=>!category||x.m[1]===category);if(!list.length)list=messages.map((m,i)=>({m,i}));let pick=list[Math.floor(Math.random()*list.length)];if(list.length>1&&pick.i===current)pick=list[(list.findIndex(x=>x.i===current)+1)%list.length];setMessage(pick.i);statusEl.textContent=`${pick.m[1]} • mensagem recebida 🙏`;setTimeout(()=>statusEl.textContent="",1800)}
$("newBtn").onclick=()=>newMessage();
document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>newMessage(b.dataset.cat));
$("headerFavBtn").onclick=()=>{const f=favorites();if(!f.includes(current))f.push(current);else f.splice(f.indexOf(current),1);localStorage.setItem("fe_favoritos",JSON.stringify(f));renderFavorites();statusEl.textContent="Favoritos atualizados ❤️"};
$("favNav").onclick=()=>{document.querySelector('.favorites-section').scrollIntoView({behavior:'smooth'});};
$("showFavs").onclick=()=>document.querySelector('.favorites-section').scrollIntoView({behavior:'smooth'});
async function share(){const text=`🙏 Mensagem de Fé\n\n${messages[current][0]}\n\n${messages[current][2]}`;try{if(navigator.share)await navigator.share({title:"Mensagem de Fé",text});else{await navigator.clipboard.writeText(text);statusEl.textContent="Mensagem copiada para compartilhar 🙏"}}catch(e){}}
$("shareBtn").onclick=share;$("shareNav").onclick=share;
$("speakBtn").onclick=()=>{if(!('speechSynthesis'in window)){statusEl.textContent="Seu navegador não oferece leitura em voz alta.";return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(messages[current][0]);u.lang="pt-BR";u.rate=.9;speechSynthesis.speak(u)};
$("messagesNav").onclick=()=>newMessage();$("settingsNav").onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('fe_tema',document.body.classList.contains('dark')?'dark':'light')};$("menuBtn").onclick=()=>statusEl.textContent="Em breve: menu de categorias e configurações ✨";
if(localStorage.getItem("fe_tema")==="dark")document.body.classList.add("dark");
let deferredPrompt;const installBtn=$("installBtn");window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove("hidden")});installBtn.onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add("hidden")};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));setMessage(0);