const messages=[
["Que a sua fé seja maior que os seus medos. Deus está cuidando de você.","Fé"],["Quando tudo parecer difícil, lembre-se: você não está sozinho. Deus caminha com você.","Esperança"],["Entregue a Deus aquilo que você não consegue controlar e confie no tempo dEle.","Confiança"],["Que Deus ilumine seus caminhos, proteja sua família e encha seu coração de paz.","Proteção"],["Não desista. Muitas vezes a bênção está mais perto do que você imagina.","Força"],["Comece o dia agradecendo. Cada novo amanhecer é uma oportunidade de recomeçar.","Bom dia"],["Que a paz de Deus entre em sua casa e permaneça em seu coração nesta noite.","Boa noite"],["Tenha coragem para continuar. Deus conhece suas lutas e vê cada lágrima.","Força"],["A oração muda o coração, fortalece a esperança e nos aproxima de Deus.","Oração"],["Mesmo sem entender o caminho, continue confiando. Deus sabe para onde está levando você.","Confiança"],["Que nunca falte fé para acreditar, força para continuar e esperança para recomeçar.","Esperança"],["Deus pode transformar um momento difícil em um testemunho de vitória.","Vitória"]
];
let current=0;
const messageEl=document.getElementById("message"),categoryEl=document.getElementById("category"),favBtn=document.getElementById("favBtn"),statusEl=document.getElementById("status");
function showMessage(i){current=i;messageEl.textContent=messages[i][0];categoryEl.textContent=messages[i][1];updateFavorite()}
function updateFavorite(){const f=JSON.parse(localStorage.getItem("fe_favoritos")||"[]");favBtn.textContent=f.includes(current)?"♥ Favoritada":"♡ Favoritar"}
document.getElementById("newBtn").onclick=()=>{let n=Math.floor(Math.random()*messages.length);if(messages.length>1&&n===current)n=(n+1)%messages.length;showMessage(n);statusEl.textContent="Nova mensagem recebida 🙏";setTimeout(()=>statusEl.textContent="",1800)};
favBtn.onclick=()=>{let f=JSON.parse(localStorage.getItem("fe_favoritos")||"[]");if(f.includes(current))f=f.filter(x=>x!==current);else f.push(current);localStorage.setItem("fe_favoritos",JSON.stringify(f));updateFavorite()};
document.getElementById("shareBtn").onclick=async()=>{const text=`🙏 Mensagem de Fé\n\n${messages[current][0]}\n\n${location.href}`;try{if(navigator.share)await navigator.share({title:"Mensagem de Fé",text});else{await navigator.clipboard.writeText(text);statusEl.textContent="Mensagem copiada para compartilhar 🙏"}}catch(e){}};
document.getElementById("speakBtn").onclick=()=>{if(!( "speechSynthesis" in window)){statusEl.textContent="Seu navegador não oferece leitura em voz alta.";return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(messages[current][0]);u.lang="pt-BR";u.rate=.9;speechSynthesis.speak(u)};
document.getElementById("themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("fe_tema",document.body.classList.contains("dark")?"dark":"light")};
if(localStorage.getItem("fe_tema")==="dark")document.body.classList.add("dark");
let deferredPrompt;const installBtn=document.getElementById("installBtn");window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove("hidden")});installBtn.onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add("hidden")};
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));showMessage(0);
